name: "Build Libs"

on:
  schedule:
    - cron: '* 5 * * *'

jobs:
  LibBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2

      - name: Build Lib
        run: javac src/it/tn/buonarroti/masala/utils/Data.java

      - name: Compress lib
        run: jar cf FraLibs.jar src/it/tn/buonarroti/masala/utils/Data.class
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
           name: FraLibs.jar
           path: FraLibs.jar
