name: "Build Libs"

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '* 5 * * *'

jobs:
  LibBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Build Lib
        run: javac src/me/francescomasala/school/libs/utils/*.java

      - name: Compress lib
        run: jar cf Libs.jar src/me/francescomasala/school/libs/utils/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            draft: false
            prerelease: false
            automatic_release_tag: CI
            title: Libs
            files: Libs.jar